version: '3.9'

services:
  orders:
    build:
      context: ./OrdesServices
      dockerfile: Dockerfile
    restart: always
    volumes:
      - orders-db-data:/app/db-data
    ports:
      - "8000:8000"
  products:
    build:
      context: ./ProductServices
      dockerfile: Dockerfile
    restart: always
    volumes:
      - products-db-data:/app/db-data
    ports:
      - "8001:8000"
volumes:
  orders-db-data:
  products-db-data:
